# Generated by Django 4.1.5 on 2023-01-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_productinventory_is_on_sale_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='productattributevalues',
            options={'verbose_name_plural': 'Products attributes values'},
        ),
        migrations.AlterModelOptions(
            name='productinventory',
            options={'verbose_name_plural': 'Product Inventory'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': 'Stock'},
        ),
    ]
