# Generated by Django 4.1.5 on 2023-01-06 17:49

import apps.inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_media_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='img_url',
            field=models.ImageField(default='products/default.jpg', upload_to=apps.inventory.models.Media.upload_to, verbose_name='Image'),
        ),
    ]
